### ISSUE TITLE
Mysterious 404 when trying to release

### ISSUE THREAD

**Issue by antony** [webpro/release-it#172]
I appear to be getting some sort of 404 when I try to release.

```bash
✔ Bump version
✔ Git commit
✔ Git tag
✔ Git push
✖ GitHub release
ERROR 404 Not Found: Not Found ()
```
My configuration is very simple:
```json
{
  "github": {
    "release": true,
    "assets": "dist/merchant-package-*",
    "tokenRef": "RELEASE_GITHUB_TOKEN"
  },
  "src": {
    "tagName": "v%s"
  }
}
```

and I'm running the following command to release (from CI, but this error is encountered running locally:

```bash
release-it -n minor
```

**Comment by webpro** [comment]
Hi, @antony! Can you please update release-it to (at least) v5.0.1, and see if there's any useful output regarding the error you see. This can be done by adding `--verbose` to see what commands are being executed, and `--debug` to get extra debug output:

```
release-it minor --debug --verbose
```

**Comment by cschweda** [comment]
I get the same 404 error. I added the token, too.

Version:
```
release-it -v
v5.1.2
```
Error:

```
REQUEST:  { host: 'api.github.com',
  port: 443,
  path: '/repos/ICJIA/icjia-redeploy/releases?access_token=TOKEN_REMOVED',
  method: 'post',
  headers:
   { host: 'api.github.com',
     'content-length': 111,
     'content-type': 'application/json; charset=utf-8',
     'user-agent': 'webpro/release-it',
     accept: 'application/vnd.github.v3+json' },
  ca: undefined,
  family: undefined }
REQUEST BODY: {"tag_name":"0.2.0","name":"Release 0.2.0","body":"* Release 0.1.4 (9515a88)","draft":false,"prerelease":false}

STATUS: 404
HEADERS: {"server":"GitHub.com","date":"Fri, 15 Dec 2017 16:48:23 GMT","content-type":"application/json; charset=utf-8","content-length":"110","connection":"close","status":"404 Not Found","x-ratelimit-limit":"5000","x-ratelimit-remaining":"4996","x-ratelimit-reset":"1513359980","x-oauth-scopes":"","x-accepted-oauth-scopes":"","x-github-media-type":"github.v3; format=json","access-control-expose-headers":"ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval","access-control-allow-origin":"*","content-security-policy":"default-src 'none'","strict-transport-security":"max-age=31536000; includeSubdomains; preload","x-content-type-options":"nosniff","x-frame-options":"deny","x-xss-protection":"1; mode=block","x-runtime-rack":"0.030196","x-github-request-id":"D9B8:06B2:F3F25:23B6C9:5A33FCD7"}
[error] { [Error: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/releases/#create-a-release"}]
[error]   message: '{"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/releases/#create-a-release"}',
[error]   code: 404,
[error]   status: 'Not Found',
[error]   headers:
[error]    { server: 'GitHub.com',
[error]      date: 'Fri, 15 Dec 2017 16:48:23 GMT',
[error]      'content-type': 'application/json; charset=utf-8',
[error]      'content-length': '110',
[error]      connection: 'close',
[error]      status: '404 Not Found',
[error]      'x-ratelimit-limit': '5000',
[error]      'x-ratelimit-remaining': '4996',
[error]      'x-ratelimit-reset': '1513359980',
[error]      'x-oauth-scopes': '',
[error]      'x-accepted-oauth-scopes': '',
[error]      'x-github-media-type': 'github.v3; format=json',
[error]      'access-control-expose-headers': 'ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
[error]      'access-control-allow-origin': '*',
[error]      'content-security-policy': 'default-src \'none\'',
[error]      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
[error]      'x-content-type-options': 'nosniff',
[error]      'x-frame-options': 'deny',
[error]      'x-xss-protection': '1; mode=block',
[error]      'x-runtime-rack': '0.030196',
[error]      'x-github-request-id': 'D9B8:06B2:F3F25:23B6C9:5A33FCD7' } } { owner: 'ICJIA',
[error]   repo: 'icjia-redeploy',
[error]   tag_name: '0.2.0',
[error]   name: 'Release 0.2.0',
[error]   body: '* Release 0.1.4 (9515a88)',
[error]   prerelease: false,
[error]   draft: false } null
ERROR 404 Not Found: Not Found ()
  release-it:catchall Error: 404 Not Found: Not Found ()
  release-it:catchall     at githubClient.repos.createRelease (/usr/local/lib/node_modules/release-it/lib/github-client.js:90:22)
  release-it:catchall     at module.exports.__dirname.sendError (/usr/local/lib/node_modules/release-it/node_modules/github/lib/index.js:874:7)
  release-it:catchall     at /usr/local/lib/node_modules/release-it/node_modules/github/lib/index.js:882:21
  release-it:catchall     at callCallback (/usr/local/lib/node_modules/release-it/node_modules/github/lib/index.js:738:9)
  release-it:catchall     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/release-it/node_modules/github/lib/index.js:807:13)
  release-it:catchall     at IncomingMessage.emit (events.js:164:20)
  release-it:catchall     at endReadableNT (_stream_readable.js:1054:12)
  release-it:catchall     at _combinedTickCallback (internal/process/next_tick.js:138:11)
  release-it:catchall     at process._tickCallback (internal/process/next_tick.js:180:9) +13s
  release-it:catchall { statusCode: 200,
  release-it:catchall   statusMessage: 'OK',
  release-it:catchall   url: 'http://www.google-analytics.com/collect' } +146ms
```

**Comment by webpro** [comment]
* Maybe the tag (`tag_name`) can't be found when doing the release. Does it include the `v` in the Git repo (and on gitHub)?
* Is this a GitHub private or a enterprise repo?

**Comment by nielsgl** [comment]
I had the same problem today, and at least in my case it was about a private repo within an organization. I had to update the token permissions (add `admin:org_hook` permission) and that solved the problem and it all works now 👍  🎉

**Comment by webpro** [comment]
Thanks, @nielsgl! I'll update the readme with this information.

**Comment by antony** [comment]
Sorry, didn't get around to responding to this as I left the company! Glad you've found a solution @nielsgl + @webpro
