### ISSUE TITLE
Uploading Github assets fails with `ERROR Empty value for parameter 'file': undefined`

### ISSUE THREAD

**Issue by LrsNate** [webpro/release-it#212]
Hi guys, happy new year!

First of all thanks for this tool, saves me tons of time, really appreciate :) I've started getting problems with asset uploading: the Github release is created but the assets can't be uploaded to it (to clarify it used to work with that exact setup, then I started having that problem without updating release-it AFAIK). I've added some logs here:

```
$ node-github releases#uploadAsset
  release-it:github-client SyntaxError: Unexpected token E in JSON at position 0
  release-it:github-client     at JSON.parse (<anonymous>)
  release-it:github-client     at parseErrorMessage (/Users/Nate/Code/Fourmi/node_modules/release-it/lib/github-client.js:43:27)
  release-it:github-client     at githubClient.repos.uploadAsset (/Users/Nate/Code/Fourmi/node_modules/release-it/lib/github-client.js:132:27)
  release-it:github-client     at module.exports.__dirname.sendError (/Users/Nate/Code/Fourmi/node_modules/github/lib/index.js:796:7)
  release-it:github-client     at Object.self.(anonymous function).(anonymous function) [as uploadAsset] (/Users/Nate/Code/Fourmi/node_modules/github/lib/index.js:249:20)
  release-it:github-client     at Promise (/Users/Nate/Code/Fourmi/node_modules/release-it/lib/github-client.js:122:28)
  release-it:github-client     at new Promise (<anonymous>)
  release-it:github-client     at retry (/Users/Nate/Code/Fourmi/node_modules/release-it/lib/github-client.js:121:7)
  release-it:github-client     at RetryOperation.op.attempt.num [as _fn] (/Users/Nate/Code/Fourmi/node_modules/async-retry/lib/index.js:31:15)
  release-it:github-client     at Timeout._onTimeout (/Users/Nate/Code/Fourmi/node_modules/retry/lib/retry_operation.js:68:10)
  release-it:github-client     at ontimeout (timers.js:466:11)
  release-it:github-client     at tryOnTimeout (timers.js:304:5)
  release-it:github-client     at Timer.listOnTimeout (timers.js:264:5) +1ms
```

This block is repeated 5 times in the logs. I'm running `v5.2.0`, and here's my `release-it.json`

```
{
  "buildCommand": "yarn clean && yarn dist",
  "src": {
    "tagName": "v%s"
  },
  "github": {
    "release": true,
    "assets": "dist/*.{dmg,zip}"
  }
}
```

Is there something I'm doing wrong? Sorry I don't have much more info to try and diagnose.

Cheers,
Nate

**Comment by webpro** [comment]
The upload asset API has been changed in node-github v13 (https://github.com/octokit/rest.js/releases/tag/v13.0.0).

I will fix this. This is broken since release v5.2.0. You could downgrade to v5.1.3 (or earlier) in the meantime.

**Comment by webpro** [comment]
Should be fixed with [v6.1.1](https://github.com/webpro/release-it/releases/tag/6.1.1)

**Comment by LrsNate** [comment]
Confirmed on v6.1.1. Thank you 👍

**Comment by webpro** [comment]
Thanks for confirming this, @LrsNate
