### ISSUE TITLE
Error on first run when allowed reporting of usage statistics

### ISSUE THREAD

**Issue by petersandor** [webpro/release-it#29]
Hi, I just installed this module and I got this error on first run (after accepting the tracking prompt). Running `npm v2.11.3` and `node v0.12.7` on Win7 x64.
```
C:\Projects\test (master)
λ release-it
? May release-it anonymously report usage statistics to improve the tool over time? Yes
C:\Users\user\AppData\Roaming\npm\node_modules\release-it\node_modules\insight\node_modules\inquirer\node_modules\rx\dist\rx.js:579
    throw e;
          ^
TypeError: undefined is not a function
    at C:\Users\user\AppData\Roaming\npm\node_modules\release-it\lib\tracker.js:36:22
    at Insight.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\release-it\node_modules\insight\lib\index.js:116:3)
    at PromptUI.onCompletion (C:\Users\user\AppData\Roaming\npm\node_modules\release-it\node_modules\insight\node_modules\inquirer\lib\ui\prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (C:\Users\user\AppData\Roaming\npm\node_modules\release-it\node_modules\insight\node_modules\inquirer\node_modules\rx\dist\rx.js:1793:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\user\AppData\Roaming\npm\node_modules\release-it\node_modules\insight\node_modules\inquirer\node_modules\rx\dist\rx.js:1730:14)
    at AnonymousObserver.tryCatcher (C:\Users\user\AppData\Roaming\npm\node_modules\release-it\node_modules\insight\node_modules\inquirer\node_modules\rx\dist\rx.js:567:29)
    at AutoDetachObserverPrototype.completed (C:\Users\user\AppData\Roaming\npm\node_modules\release-it\node_modules\insight\node_modules\inquirer\node_modules\rx\dist\rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\user\AppData\Roaming\npm\node_modules\release-it\node_modules\insight\node_modules\inquirer\node_modules\rx\dist\rx.js:1730:14)
    at InnerObserver.onCompleted (C:\Users\user\AppData\Roaming\npm\node_modules\release-it\node_modules\insight\node_modules\inquirer\node_modules\rx\dist\rx.js:3425:65)
    at InnerObserver.tryCatcher (C:\Users\user\AppData\Roaming\npm\node_modules\release-it\node_modules\insight\node_modules\inquirer\node_modules\rx\dist\rx.js:567:29)
```

Consecutive runs are without this issue.

**Comment by webpro** [comment]
Thanks for not ignoring the error, @petersandor! Just released a fix in v0.1.4.
