### ISSUE TITLE
Unhelpful error message for malformed config file

### ISSUE THREAD

**Issue by maiamcc** [webpro/release-it#307]
If I have bad json in `.release-it.json`, I get a `FileNotFoundError`, which is confusing b/c the file IS there -- the problem is the json syntax.

**Repro steps:**

`.release-it.json` contents:
```{
  "github": {
    "release": true,
    "tokenRef": "GITHUB_TOKEN",
    "assets": "dist/*.zip"
  }
```
(This is bad JSON -- note missing curly bracket)

Error message:
```$ release-it --dry-run
/usr/local/lib/node_modules/release-it/lib/config.js:36
      throw new FileNotFoundError(localOptionsPath);
      ^

Error: File not found (/Users/maia/code/go/src/github.com/windmilleng/mish/.release-it.json)
    at getLocalOptions (/usr/local/lib/node_modules/release-it/lib/config.js:36:13)
    at new Config (/usr/local/lib/node_modules/release-it/lib/config.js:62:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/release-it/lib/config.js:166:25)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

When I correct the JSON syntax, `release-it` runs correctly.

**Comment by webpro** [comment]
Thanks, @maiamcc! Not sure how this happened, but it's fixed now in [v7.4.6](https://github.com/webpro/release-it/releases/tag/7.4.6).
