### ISSUE TITLE
Cannot seem to turn off git pushing

### ISSUE THREAD

**Issue by StephanBijzitter** [webpro/release-it#362]
```bash
yarn release-it pre --prereleaseId=foo --npm.tag=beta --npm.publish --non-interactive --no-src.push --no-src.commit --no-src.tag --no-github.release --dry-run
```

```
[dry-run] git config --get remote.origin.url
https://stephanbijzitter@github.com/<secret>/<secret>.git
Release source repo
[dry-run] git rev-parse --git-dir
/Users/stephan/<secret>/<secret>/.git
[dry-run] bump [ 'package.json' ] 4.5.6-foo.0
[verbose] No build command was provided.
[dry-run] git add package.json
[dry-run] git diff-index --name-only HEAD --exit-code
scripts/codeship/prepublish.sh
[dry-run] git commit --message="Release 4.5.6-foo.0"
[dry-run] git tag --annotate --message="Release 4.5.6-foo.0" 4.5.6-foo.0
[dry-run] git push --follow-tags 
[dry-run] npm publish . --tag beta
[verbose] No "dist.repo" configuration provided, done.
```

I _only_ want to publish to npm, but our CI crashes on the failed pushing to Github. I tried turning off the pushing, but I seem to be unable to do that.

What am I doing wrong?

**Comment by webpro** [comment]
Can you reproduce the issue, e.g. on your own machine?

**Comment by StephanBijzitter** [comment]
Yes, the OP's log is from my own machine.

The following is a log from our CI:
```
Identifying the module to prepublish...
Comparing current branch to remote master...
Found 2 changed files.
Generating list of changed modules...
Setting up read-write private NPM...
Attempting to prepublish fabric-modules...
[execute] git config --get remote.origin.url
git@github.com:<private>/<private>-Node.git
Release source repo
[execute] git rev-parse --git-dir
/home/rof/src/github.com/<private>/<private>-Node/.git
[execute] bump package.json 4.5.7-cb0eb2381b4fbdf64ab61bee66592fc81eaef477.0
No build command was provided.
[execute] git add package.json
[execute] git diff-index --name-only HEAD --exit-code
modules/fabric-modules/package.json
modules/github-ci/bin/gci.js
[execute] git commit  --message="Release 4.5.7-cb0eb2381b4fbdf64ab61bee66592fc81eaef477.0" .
[detached HEAD fcef44a] Release 4.5.7-cb0eb2381b4fbdf64ab61bee66592fc81eaef477.0
1 file changed, 1 insertion(+), 1 deletion(-)
[execute] git tag  --annotate --message="Release 4.5.7-cb0eb2381b4fbdf64ab61bee66592fc81eaef477.0" 4.5.7-cb0eb2381b4fbdf64ab61bee66592fc81eaef477.0
[execute] git push 
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

git push origin HEAD:<name-of-remote-branch>

ERROR Please make sure an upstream remote repository is configured for the current branch. Example commands:
git remote add origin git@github.com:<private>/<private>-Node.git
git push --set-upstream origin master
ERROR Error
at run.catch.err (/home/rof/src/github.com/<private>/<private>-Node/node_modules/release-it/lib/git.js:128:11)
at tryCatchReject (/home/rof/src/github.com/<private>/<private>-Node/node_modules/when/lib/makePromise.js:845:30)
at runContinuation1 (/home/rof/src/github.com/<private>/<private>-Node/node_modules/when/lib/makePromise.js:804:4)
at Rejected.when (/home/rof/src/github.com/<private>/<private>-Node/node_modules/when/lib/makePromise.js:625:4)
at Pending.run (/home/rof/src/github.com/<private>/<private>-Node/node_modules/when/lib/makePromise.js:483:13)
at Scheduler._drain (/home/rof/src/github.com/<private>/<private>-Node/node_modules/when/lib/Scheduler.js:62:19)
at Scheduler.drain (/home/rof/src/github.com/<private>/<private>-Node/node_modules/when/lib/Scheduler.js:27:9)
at _combinedTickCallback (internal/process/next_tick.js:132:7)
at process._tickCallback (internal/process/next_tick.js:181:9)
```

Generated by running this bash script:
```bash
#!/usr/bin/env bash

shopt -s cdable_vars;
source ${GIT_ROOT}/scripts/common/config.sh;

echo "Identifying the module to prepublish...";
cd ${GIT_ROOT};
    echo "Comparing current branch to remote master...";
    files=($(getChangedFiles origin/master ${CI_BRANCH}));
    files_count=${#files[@]};
    echo "Found ${files_count} changed files.";

    echo "Generating list of changed modules...";
    modules=($(getModuleNames "${files[@]}"));
    module=${modules[0]};

    if [ -z ${module} ]; then
        echo "Failed to identify a module to prepublish.";
        exit 0;
    fi;

echo "Setting up read-write private NPM...";
> ${HOME}/.npmrc;
npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN_WRITE};

echo "Attempting to prepublish ${module}...";
cd ${GIT_ROOT}/modules/${module};
    ${GIT_ROOT}/node_modules/.bin/release-it pre --prereleaseId=${CI_COMMIT_ID} --npm.tag=beta --npm.publish --non-interactive;
```

**Comment by webpro** [comment]
I'm a bit surprised by this line:

```
[execute] git push 
```

Since I think it should at least print `git push --follow-tags` (like in the dry run). What version of release-it are you using on the CI environment?

Also, you can use the `requireUpstream: false` or `--no-requireUpstream` option to have release-it add this to the push command:

```
--set-upstream origin ${branchName}
```

But I'm not sure whether Git will return `master` here.
