### ISSUE TITLE
`use strict`

### ISSUE THREAD

**Issue by destroyerofbuilds** [webpro/release-it#88]
A few fellow developers are encountering the following error:

```bash
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/user/wcheung/public_html/news-applications/news-doc-app-framework/node_modules/release-it/lib/log.js:3:12)
```

It seems, to be able to run code with `let` or `const` in Node 4, the file must have the `use strict` statement at the beginning.

Node 6 and later do not have this issue.

Node 4 is still widely in use, though in the _maintenance_ stage of its life,  as it's still supported by the Node LTS Working Group.

**Comment by webpro** [comment]
Thanks for catching this @destroyerofbuilds, sometimes I forget to test in Node v4. Could you please open a PR for this? Thanks!

**Comment by destroyerofbuilds** [comment]
@webpro I'm sorry I haven't submitted a pull request to address the Node 4 issue. I was trying to encourage my fellow developers at work to submit a pull request to add `use strict` statements.

Just a note, the actual error was in `lib/log.js`, which is still missing the `use strict` statement.

**Comment by webpro** [comment]
No problem. I've put the statement in another file, but I guess it's applied to other modules loaded as well.
